# Generated by Django 4.1 on 2023-05-01 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('coin_symbol', models.CharField(max_length=10, unique=True, verbose_name='coin_symbol')),
            ],
            options={
                'verbose_name': 'CoinSymbol',
                'verbose_name_plural': 'CoinSymbols',
            },
        ),
        migrations.CreateModel(
            name='CoinPriceAllChartMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField(verbose_name='price')),
                ('trade_timestamp', models.DateField(verbose_name='all_coin_trade_time')),
                ('coin_symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.coinsymbol', verbose_name='coin_symbol_fore')),
            ],
            options={
                'verbose_name': 'CoinPriceAllChartMarket',
                'verbose_name_plural': 'CoinPriceAllChartMarkets',
            },
        ),
    ]
